#v.0.1.0

[global]
testName="MySQL_all_tpcc_optimized"
logLevel = "info"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/tmp/sysbench_graph_creator.log"

[parser]
sourceDataPath="D:\\work\\blogs\\2024\\sakila_where_are_you_going\\tpcc\\optimized\\logs\\"
#sourceDataPath="D:\\work\\blogs\\2024\\sakila_where_are_you_going\\sysbench\\optimized\\logs\\"
#sourceDataPath="D:\\work\\percona\\Tech_Lead\\Projects\\operator_testing\\everest_010\\sysbench_scenarios_increase_writes"
#sourceDataPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\compare_oracle_840\\logs"
#sourceDataPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\PS_VS_MYS_8036_optimized\\logs"
#sourceDataPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\all_together\\optimized\\logs"
#sourceDataPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\tpcc\\PS-VS-MY8036"
#sourceDataPath="D:\\work\\percona\\Tech_Lead\\Projects\\operator_testing\\everest_010\\logs"
#sourceDataPath="/Users/marcotusa/work/percona/Tech_Lead/Projects/Benchmarking_procedures/not_processed/sysbench/MY-PS-8034-NO-AHI"
filterOutliners = true
distanceLabel = "operations/s"


[render]
graphType="column"
destinationPath="D:\\work\\blogs\\2024\\sakila_where_are_you_going\\tpcc\\optimized\\all"
#destinationPath="D:\\work\\blogs\\2024\\sakila_where_are_you_going\\sysbench\\optimized\\all"
#destinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\operator_testing\\everest_010\\sysbench_scenarios_increase_writes"
#destinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\compare_oracle_840"
#destinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\all_together\\optimized"
#destinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\PS_VS_MYS_8036_optimized"
#destinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\for_report\\tpcc\\PS-VS-MY8036"
#destinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\operator_testing\\everest_010\\logs"
csvDestinationPath=""
printStats=false
printData=false
printCharts=false
convertChartsToCsv=true


httpServerPort=8089
httpServerIp="localhost"
#labels="operations/s"
#labels="operations/s,latencyPct95(μs)"
labels="TotalTime,Events/s,operations/s,writes/s,reads/s,latencyPct95(μs)"
#labels="writes/s,reads/s"
statslabels="operations/s,latencyPct95(μs)"
readSummaryLabel="reads/s"
writeSummaryLabel="writes/s"
#labels="TotalTime,RunningThreads,totalEvents,Events/s,Tot Operations,operations/s,tot reads,reads/s,Tot writes,writes/s,oterOps/s,latencyPct95(μs) ,Tot errors,errors/s,Tot reconnects,reconnects/s,Latency(ms) min, Latency(ms) max, Latency(ms) avg, Latency(ms) sum"
#//TODO start
showReads=true
showWrites=true
showPreWrite=true
shoPostWrite=true
filterTestBy=""
#//TODO end
chartHeight=500
chartWidth=1200
printChartsFormat="jpeg"

[colors]
color=[
    "name=Percona;version=8.0;color=#0e1a53"
    ,"name=Percona;version=9.0;color=#117e1a "
    ,"name=Percona;version=8.4;color=#ff7e1a"
    ,"name=Percona;version=5.7;color=#f0b336"
    ,"name=MySQL;version=5.7;color=#bac0cd"
    ,"name=MySQL;version=8.0;color=#93c7ff"
    ,"name=MySQL;version=8.4;color=#f9a98a"
    ,"name=Maria;version=11.3;color=#f24500"
]

