#v.0.1.0
[parser]
sourceDataPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\benchmark_exercise_december_2024_q1_2025\\results"
#sourceDataPath="D:\\work\\blogs\\2024\\sakila_where_are_you_going\\sysbench\\base\\logs\\onlymysql"
#sourceDataPath="/Users/marcotusa/work/blogs/2024/sakila_where_are_you_going/sysbench/base/logs"
#sourceDataPath="/Users/marcotusa/work/percona/Tech_Lead/Projects/Benchmarking_procedures/for_report/PS_VS_MYS_8036_optimized/logs" #MY-PS-8034-BASE

#sourceDataPath="/Users/marcotusa/work/percona/Tech_Lead/Projects/Benchmarking_procedures/not_processed/sysbench/MY-PS-8034-NO-AHI"
filterOutliners = true
distanceLabel = "operations/s"

[render]
graphType="column"
destinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\benchmark_exercise_december_2024_q1_2025\\results\\compare-blade-thebeast"
#destinationPath="D:\\work\\blogs\\2024\\sakila_where_are_you_going\\sysbench\\base\\"
#destinationPath="/Users/marcotusa/work/blogs/2024/sakila_where_are_you_going/sysbench/base"
#destinationPath="/Users/marcotusa/work/blogs/2024/sakila_where_are_you_going/sysbench/base/logs"
#csvDestinationPath="D:\\work\\percona\\Tech_Lead\\Projects\\Benchmarking_procedures\\benchmarking_on_hetzner\\results\\all\\csv\\small"
csvDestinationPath=""
printStats=false
printData=true
convertChartsToCsv=false
printCharts=false

httpServerPort=8089
httpServerIp="localhost"
#labels=""
labels="operations/s"
#labels="operations/s,latencyPct95(μs)"
#labels="TotalTime,Events/s,operations/s,writes/s,reads/s,latencyPct95(μs)"
statslabels="operations/s,latencyPct95(μs)"
readSummaryLabel="reads/s"
writeSummaryLabel="writes/s"
#labels="TotalTime,RunningThreads,totalEvents,Events/s,Tot Operations,operations/s,tot reads,reads/s,Tot writes,writes/s,oterOps/s,latencyPct95(μs) ,Tot errors,errors/s,Tot reconnects,reconnects/s,Latency(ms) min, Latency(ms) max, Latency(ms) avg, Latency(ms) sum"
filterTestsByTitle=""
filterExcludeByTitle=""
filterByDimension=""
filterByVersion=""
filterByProducer=""
filterByPrePost=""
#filterTestsBy="select_run_range,write_run_update_no_index"

chartHeight=400
chartWidth=800
printChartsFormat="jpeg"


[global]
testName="Comparing MySQL Versions 5.7 to 9.0"
logLevel = "debug"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/tmp/sysbench_graph_creator.log"

[colors]
color=[
    "name=Percona;version=8.0;color=#0e1a53"
    ,"name=Percona;version=9.1;color=#117e1a"
    ,"name=Percona;version=9.2;color=#184f1d"
    ,"name=Percona;version=9.3;color=#36763c"
    ,"name=Percona;version=9.4;color=#27842f"
    ,"name=Percona;version=8.4.3;color=#ff7e1a"
    ,"name=Percona;version=8.4.4;color=#6db8f2"
    ,"name=Percona;version=8.4.5;color=#9fcdf0"
    ,"name=Percona;version=5.7;color=#f0b336"
    ,"name=MySQL;version=5.7;color=#bac0cd"
    ,"name=MySQL;version=8.0;color=#93c7ff"
    ,"name=MySQL;version=8.4;color=#f9a98a"
    ,"name=MySQL;version=8.4.4;color=#9af98a"
    ,"name=MySQL;version=8.4.5;color=#69e255"
    ,"name=MySQL;version=9.1;color=#cc3a00"
    ,"name=MySQL;version=9.2;color=#f0ca6c"
    ,"name=MySQL;version=9.3;color=#f2d99b"
    ,"name=MySQL;version=9.4;color=#f02505"
    ,"name=Maria;version=11.6;color=#f24500"
    ,"name=Source;version=9.1;color=#1aff41"
    ,"name=Source;version=8.4.3;color=#1a9bff"
    ,"name=Source;version=8.4.4;color=#6db8f2"
    ,"name=Source;version=8.4.5;color=#9fcdf0"
    ,"name=Thebeast;version=8.0;color=#93c7ff"
]